export const DIALOG_SHOW_DM = 'DIALOG_SHOW_DM';
export const DIALOG_TOGGLE_DM = 'DIALOG_TOGGLE_DM';
export const DIALOG_DATA_IMAGE_URL = 'DIALOG_DATA_IMAGE_URL';
export const DIALOG_SET_FORM_DATA = 'DIALOG_SET_FORM_DATA';
export const DIALOG_POST_TEXT = 'DIALOG_POST_TEXT';
