
export const FRIEND_ADD_FRIENDS = 'FRIEND_ADD_FRIENDS';
export const FRIEND_UPDATE_FRIENDS = 'FRIEND_UPDATE_FRIENDS';
export const FRIEND_UNFOLLOW_FRIEND = 'FRIEND_UNFOLLOW_FRIEND';
export const FREIND_SET_FRIEND = 'FRIEND_SET_FRIEND';
export const FRIEND_ADD_POST_IDS = 'FRIEND_ADD_POST_IDS';
export const FRIEND_ADD_TO_FRIENDS = "FRIEND_ADD_TO_FRIENDS";
export const FRIEND_GROW_FRIENDS = "FRIEND_GROW_FRIENDS";
export const FRIEND_ADD_FRIENDS_BYID = "FREIND_ADD_FRIENDS_BYID";
export const FRIEND_ADD_FRIEND_IDS = "FRIEND_ADD_FRIEND_IDS";
export const FRIEND_ADD_TO_FRIENDS_BYID = "FRIEND_ADD_TO_FRIENDS_BYID";
