export const SHOW_SEARCH_FORM = "SHOW_SEARCH_FORM";
export const ADD_QUERY_TEXT = "ADD_QUERY_TEXT";
export const HANDLE_SEARCH = "HANDLE_SEARCH";
export const SEARCH_STARTED = "SEARCH_STARTED";
export const SEARCH_SUCCEEDED = "SEARCH_SUCCEEDED";
export const SEARCH_FAILED = "SEARCH_FAILED";
export const SET_SEARCH_FILTER = "SET_SEARCH_FILTER";