export const POST_UPLOAD_MEDIA_STARTED = 'POST_UPLOAD_MEDIA_STARTED';
export const POST_UPLOAD_MEDIA_SUCCEEDED = 'POST_UPLOAD_MEDIA_SUCCEEDED';
export const POST_UPLOAD_MEDIA_ERROR = 'POST_UPLOAD_MEDIA_ERROR';
export const POST_PROGRESS_NUMBER = 'POST_PROGRESS_NUMBER';
export const POST_ADD_POST = 'POST_ADD_POST';