export const INBOX_GET_FOLLOWERS = "INBOX_GET_FOLLOWERS";
export const INBOX_GET_FOLLOWINGS = "INBOX_GET_FOLLOWINGS";
export const INBOX_ADD_MESSAGE = "INBOX_ADD_MESSAGE";
export const INBOX_SET_CURRENT_THREAD = "INBOX_SET_CURRENT_THREAD";
export const INBOX_ADD_THREAD = "INBOX_ADD_THREAD";
export const INBOX_ADD_USER_THREADS = "INBOX_ADD_USER_THREADS";
export const INBOX_ADD_THREADS = "INBOX_ADD_THREADS";
export const INBOX_CLEAR_MESSAGES = "INBOX_CLEAR_MESSAGES";