export const USER_VIEW_PROFILE = 'USER_VIEW_PROFILE';

export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_ERROR = 'AUTH_SIGNUP_ERROR';
export const AUTH_CHECK_USERNAME = 'AUTH_CHECK_USERNAME';
export const AUTH_UPLOAD_AVATAR = 'AUTH_UPLOAD_AVATAR';
export const AUTH_TALENT_CATEGORIES = 'AUTH_TALENT_CATEGORIES';
export const AUTH_PROCESS_ONBOARDING = 'AUTH_PROCESS_ONBOARDING';
export const AUTH_SIGNUP_REDIRECT = 'AUTH_SIGNUP_REDIRECT';
export const AUTH_EDIT_PROFILE_SUCCESS = 'AUTH_EDIT_PROFILE_SUCCESS';
export const AUTH_ADD_USER_POSTS = 'AUTH_ADD_USER_POSTS';
export const AUTH_ADD_USER_COMMENTS = 'AUTH_ADD_USER_COMMENTS';
export const AUTH_TOKEN_ADD = 'AUTH_TOKEN_ADD';

